--------------------------------------------------------
--  DDL for Table AUTH_TOKENS
--------------------------------------------------------

  CREATE TABLE "SHOPLI"."AUTH_TOKENS" 
   (	"ID" VARCHAR2(36 BYTE), 
	"USER_ID" VARCHAR2(36 BYTE), 
	"REFRESH_TOKEN" CLOB, 
	"ISSUED_AT" TIMESTAMP (6), 
	"EXPIRES_AT" TIMESTAMP (6), 
	"USER_AGENT" VARCHAR2(255 BYTE), 
	"IP_ADDRESS" VARCHAR2(45 BYTE), 
	"REVOKED" NUMBER(1,0) DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("REFRESH_TOKEN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."USER_ID" IS 'Liên kết với bảng users';
   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."REFRESH_TOKEN" IS 'Lưu JWT refresh token';
   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."ISSUED_AT" IS 'Thời gian cấp token';
   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."EXPIRES_AT" IS 'Hết hạn token';
   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."USER_AGENT" IS 'Theo dõi thông tin thiết bị (tùy chọn)';
   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."IP_ADDRESS" IS 'Theo dõi thông tin thiết bị (tùy chọn)';
   COMMENT ON COLUMN "SHOPLI"."AUTH_TOKENS"."REVOKED" IS 'Nếu true, token sẽ bị từ chối khi sử dụng';
