--------------------------------------------------------
--  DDL for Table TUTORIALS
--------------------------------------------------------

  CREATE TABLE "SHOPLI"."TUTORIALS" 
   (	"ID" VARCHAR2(50 CHAR), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PUBLISHED" NUMBER(1,0), 
	"CODE" VARCHAR2(200 BYTE), 
	"CATEGORY_ID" NUMBER, 
	"PARENT_ID" VARCHAR2(50 CHAR), 
	"CREATEDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
