--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SHOPLI"."USERS" 
   (	"ID" VARCHAR2(36 BYTE), 
	"NAME" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"IMAGE_URL" VARCHAR2(512 CHAR), 
	"EMAIL_VERIFIED" CHAR(1 BYTE) DEFAULT 'N', 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PROVIDER" VARCHAR2(50 CHAR), 
	"PROVIDER_ID" VARCHAR2(255 CHAR), 
	"ENABLED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SHOPLI"."USERS"."ENABLED" IS 'Trạng thái tài khoản';
